/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { ApiResponseOfArticleResponseDto } from './models/ApiResponseOfArticleResponseDto';
export type { ApiResponseOfAuthorResponseDto } from './models/ApiResponseOfAuthorResponseDto';
export type { ApiResponseOfAuthResponseDto } from './models/ApiResponseOfAuthResponseDto';
export type { ApiResponseOfboolean } from './models/ApiResponseOfboolean';
export type { ApiResponseOfCategoryResponseDto } from './models/ApiResponseOfCategoryResponseDto';
export type { ApiResponseOfCompetitionResponseDto } from './models/ApiResponseOfCompetitionResponseDto';
export type { ApiResponseOfFixtureResponseDto } from './models/ApiResponseOfFixtureResponseDto';
export type { ApiResponseOfIEnumerableOfArticleResponseDto } from './models/ApiResponseOfIEnumerableOfArticleResponseDto';
export type { ApiResponseOfIEnumerableOfAuthorResponseDto } from './models/ApiResponseOfIEnumerableOfAuthorResponseDto';
export type { ApiResponseOfIEnumerableOfCategoryResponseDto } from './models/ApiResponseOfIEnumerableOfCategoryResponseDto';
export type { ApiResponseOfIEnumerableOfCompetitionResponseDto } from './models/ApiResponseOfIEnumerableOfCompetitionResponseDto';
export type { ApiResponseOfIEnumerableOfFixtureResponseDto } from './models/ApiResponseOfIEnumerableOfFixtureResponseDto';
export type { ApiResponseOfIEnumerableOfPlayerResponseDto } from './models/ApiResponseOfIEnumerableOfPlayerResponseDto';
export type { ApiResponseOfIEnumerableOfPlayerTeamHistoryResponseDto } from './models/ApiResponseOfIEnumerableOfPlayerTeamHistoryResponseDto';
export type { ApiResponseOfIEnumerableOfResultResponseDto } from './models/ApiResponseOfIEnumerableOfResultResponseDto';
export type { ApiResponseOfIEnumerableOfStandingResponseDto } from './models/ApiResponseOfIEnumerableOfStandingResponseDto';
export type { ApiResponseOfIEnumerableOfTagResponseDto } from './models/ApiResponseOfIEnumerableOfTagResponseDto';
export type { ApiResponseOfIEnumerableOfTeamResponseDto } from './models/ApiResponseOfIEnumerableOfTeamResponseDto';
export type { ApiResponseOfIEnumerableOfTransferResponseDto } from './models/ApiResponseOfIEnumerableOfTransferResponseDto';
export type { ApiResponseOfIEnumerableOfUserResponseDto } from './models/ApiResponseOfIEnumerableOfUserResponseDto';
export type { ApiResponseOfIEnumerableOfVideoResponseDto } from './models/ApiResponseOfIEnumerableOfVideoResponseDto';
export type { ApiResponseOfPlayerResponseDto } from './models/ApiResponseOfPlayerResponseDto';
export type { ApiResponseOfPlayerTeamHistoryResponseDto } from './models/ApiResponseOfPlayerTeamHistoryResponseDto';
export type { ApiResponseOfResultResponseDto } from './models/ApiResponseOfResultResponseDto';
export type { ApiResponseOfStandingResponseDto } from './models/ApiResponseOfStandingResponseDto';
export type { ApiResponseOfTagResponseDto } from './models/ApiResponseOfTagResponseDto';
export type { ApiResponseOfTeamResponseDto } from './models/ApiResponseOfTeamResponseDto';
export type { ApiResponseOfTransferResponseDto } from './models/ApiResponseOfTransferResponseDto';
export type { ApiResponseOfUserResponseDto } from './models/ApiResponseOfUserResponseDto';
export type { ApiResponseOfVideoResponseDto } from './models/ApiResponseOfVideoResponseDto';
export type { ArticleResponseDto } from './models/ArticleResponseDto';
export type { AuthorResponseDto } from './models/AuthorResponseDto';
export type { AuthResponseDto } from './models/AuthResponseDto';
export type { CategoryResponseDto } from './models/CategoryResponseDto';
export type { CompetitionResponseDto } from './models/CompetitionResponseDto';
export type { ContentStatus } from './models/ContentStatus';
export type { CreateArticleDto } from './models/CreateArticleDto';
export type { CreateAuthorDto } from './models/CreateAuthorDto';
export type { CreateCategoryDto } from './models/CreateCategoryDto';
export type { CreateCompetitionDto } from './models/CreateCompetitionDto';
export type { CreateFixtureDto } from './models/CreateFixtureDto';
export type { CreatePlayerDto } from './models/CreatePlayerDto';
export type { CreatePlayerTeamHistoryDto } from './models/CreatePlayerTeamHistoryDto';
export type { CreateResultDto } from './models/CreateResultDto';
export type { CreateStandingDto } from './models/CreateStandingDto';
export type { CreateTagDto } from './models/CreateTagDto';
export type { CreateTeamDto } from './models/CreateTeamDto';
export type { CreateTransferDto } from './models/CreateTransferDto';
export type { CreateUserDto } from './models/CreateUserDto';
export type { CreateVideoDto } from './models/CreateVideoDto';
export type { ExternalAuthDto } from './models/ExternalAuthDto';
export type { FixtureResponseDto } from './models/FixtureResponseDto';
export type { LoginDto } from './models/LoginDto';
export type { PlayerResponseDto } from './models/PlayerResponseDto';
export type { PlayerTeamHistoryResponseDto } from './models/PlayerTeamHistoryResponseDto';
export type { RefreshTokenDto } from './models/RefreshTokenDto';
export type { RegisterDto } from './models/RegisterDto';
export type { ResultResponseDto } from './models/ResultResponseDto';
export type { StandingResponseDto } from './models/StandingResponseDto';
export type { TagResponseDto } from './models/TagResponseDto';
export type { TeamResponseDto } from './models/TeamResponseDto';
export type { TransferResponseDto } from './models/TransferResponseDto';
export type { UpdateArticleDto } from './models/UpdateArticleDto';
export type { UpdateAuthorDto } from './models/UpdateAuthorDto';
export type { UpdateCategoryDto } from './models/UpdateCategoryDto';
export type { UpdateCompetitionDto } from './models/UpdateCompetitionDto';
export type { UpdateFixtureDto } from './models/UpdateFixtureDto';
export type { UpdatePlayerDto } from './models/UpdatePlayerDto';
export type { UpdatePlayerTeamHistoryDto } from './models/UpdatePlayerTeamHistoryDto';
export type { UpdateResultDto } from './models/UpdateResultDto';
export type { UpdateStandingDto } from './models/UpdateStandingDto';
export type { UpdateTagDto } from './models/UpdateTagDto';
export type { UpdateTeamDto } from './models/UpdateTeamDto';
export type { UpdateTransferDto } from './models/UpdateTransferDto';
export type { UpdateUserDto } from './models/UpdateUserDto';
export type { UpdateVideoDto } from './models/UpdateVideoDto';
export type { UserResponseDto } from './models/UserResponseDto';
export type { UserRole } from './models/UserRole';
export type { VideoResponseDto } from './models/VideoResponseDto';

export { ArticlesService } from './services/ArticlesService';
export { AuthService } from './services/AuthService';
export { AuthorsService } from './services/AuthorsService';
export { CategoriesService } from './services/CategoriesService';
export { CompetitionsService } from './services/CompetitionsService';
export { FixturesService } from './services/FixturesService';
export { PlayersService } from './services/PlayersService';
export { PlayerTeamHistoriesService } from './services/PlayerTeamHistoriesService';
export { ResultsService } from './services/ResultsService';
export { StandingsService } from './services/StandingsService';
export { TagsService } from './services/TagsService';
export { TeamsService } from './services/TeamsService';
export { TransfersService } from './services/TransfersService';
export { UsersService } from './services/UsersService';
export { VideosService } from './services/VideosService';
